// Pll.v

// Generated using ACDS version 14.1 186 at 2018.04.22.12:36:36

`timescale 1 ps / 1 ps
module Pll (
		input  wire  clk_clk,           //           clk.clk
		output wire  pll_0_outclk0_clk, // pll_0_outclk0.clk
		input  wire  reset_reset_n      //         reset.reset_n
	);

	Pll_pll_0 pll_0 (
		.refclk   (clk_clk),           //  refclk.clk
		.rst      (~reset_reset_n),    //   reset.reset
		.outclk_0 (pll_0_outclk0_clk), // outclk0.clk
		.locked   ()                   // (terminated)
	);

endmodule
